version: 1.0.{build}
build:
  verbosity: minimal
deploy:
- provider: FTP
  host: ftp.myasp.net
  protocol: ftp
  username: dejanciev1-001
  password:
    secure: UJk2qgHXtDokfUeNn/TvzA==
  folder: 
  active_mode: false
